packages:
  - "apps/*"
  - "packages/*"

linkWorkspacePackages: true
preferWorkspacePackages: true

onlyBuiltDependencies:
  - "esbuild"
  - "sharp"
  - "unrs-resolver"

allowBuilds:
  esbuild: true
  sharp: true
  unrs-resolver: true
