import { Bell, CircleDollarSign, KeyRound, LockKeyhole, Save, SlidersHorizontal } from "lucide-react";
import { PageHeading } from "@/app/ui/page-heading";
import { loadDemoState } from "@/lib/load-demo-state";

export default async function SettingsPage() {
  const data = await loadDemoState();
  return (
    <div className="page-container settings-page">
      <PageHeading eyebrow="Configuration" title="Settings" description="Mode, release policy, cost limits, and safe integration controls." actions={<button className="button primary"><Save size={15}/> Save changes</button>} />
      <div className="settings-layout"><aside className="settings-nav panel"><a className="active"><SlidersHorizontal size={15}/> General</a><a><LockKeyhole size={15}/> Release policy</a><a><CircleDollarSign size={15}/> Cost controls</a><a><Bell size={15}/> Notifications</a><a><KeyRound size={15}/> Credentials</a></aside><section className="settings-content"><article className="panel settings-section"><div className="section-title"><div><p className="eyebrow">Runtime</p><h2>Demo configuration</h2></div></div><div className="form-row"><label>Demo mode<small>Controls whether deterministic fixtures are available.</small></label><select defaultValue="synthetic"><option value="synthetic">synthetic</option><option value="off">off</option></select></div><div className="form-row"><label>Integration mode<small>Mock is credential-free; live activates configured adapters.</small></label><select defaultValue="mock"><option value="mock">mock</option><option value="live">live</option></select></div><div className="form-row"><label>Synthetic data seed<small>Same seed produces byte-identical company data.</small></label><input defaultValue={data.seed} /></div></article><article className="panel settings-section"><div className="section-title"><div><p className="eyebrow">Release safety</p><h2>Gate policy</h2></div></div><div className="form-row"><label>Weighted score threshold<small>Release is blocked below this score.</small></label><input type="number" defaultValue="85" min="0" max="100" /></div><div className="toggle-row"><div><b>Block critical deterministic failures</b><small>Overrides the weighted score.</small></div><span className="toggle on"><i/></span></div><div className="toggle-row"><div><b>Require human release approval</b><small>An agent cannot approve its own risky output.</small></div><span className="toggle on"><i/></span></div></article><article className="panel settings-section credential-safety"><LockKeyhole size={21}/><div><h2>Credentials stay outside application state</h2><p>Use provider secret stores or deployment environment variables. This interface shows configuration presence only and never returns secret values.</p></div></article></section></div>
    </div>
  );
}
